- include_role:
    name: envoy

- name: Create envoy-tcp config
  become: yes
  template:
    src: "{{item}}"
    dest: "/etc/envoy/{{item}}"
    mode: '0644'
  with_items:
    - envoy-tcp.yaml
  notify:
    - restart envoy-tcp


- name: Create envoy service config
  become: yes
  template:
    src: "{{item}}"
    dest: "/etc/systemd/system/{{item}}"
    mode: '0644'
  with_items:
    - envoy-tcp.service
  notify:
    - restart envoy-tcp

- name: Enable envoy-tcp
  become: yes
  service:
    name: envoy-tcp
    state: started
    enabled: yes

- name: Allow SSH-Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 22002-22010/tcp
    permanent: yes
    state: enabled
    immediate: true

- name: Allow Minecraft-Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 25565-25566/tcp
    permanent: yes
    state: enabled
    immediate: true

- name: Allow Minecraft-Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 25575-25576/tcp
    permanent: yes
    state: enabled
    immediate: true