- include_role:
    name: envoy

- name: Create envoy-udp config
  become: yes
  template:
    src: "{{item}}"
    dest: "/etc/envoy/{{item}}"
    mode: '0644'
  with_items:
    - envoy-udp.yaml
  notify:
    - restart envoy-udp


- name: Create envoy-udp service config
  become: yes
  template:
    src: "{{item}}"
    dest: "/etc/systemd/system/{{item}}"
    mode: '0644'
  with_items:
    - envoy-udp.service
  notify:
    - restart envoy-udp

- name: Enable envoy-udp
  become: yes
  service:
    name: envoy-udp
    state: started
    enabled: yes

- name: Allow Minecraft-Bedrock Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 19132-19133/udp
    permanent: yes
    state: enabled
    immediate: true

- name: Allow Minecraft-Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 25565-25585/udp
    permanent: yes
    state: enabled
    immediate: true
