static_resources:
  listeners:
  - name: listener_19132
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 19132
    udp_listener_config:
      downstream_socket_config:
        max_rx_datagram_size: 9000
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: service
        cluster: cluster_19132
        upstream_socket_config:
          max_rx_datagram_size: 9000

{% for port in range(25565,25585) %}
  - name: listener_{{port}}
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: {{port}}
    udp_listener_config:
      downstream_socket_config:
        max_rx_datagram_size: 9000
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: service
        cluster: cluster_{{port}}
        upstream_socket_config:
          max_rx_datagram_size: 9000
{% endfor %}

  clusters:
  - name: cluster_19132
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: cluster_19132
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.100.0.2
                port_value: 19132

{% for port in range(25565,25585) %}
  - name: cluster_{{port}}
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: cluster_{{port}}
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.100.0.2
                port_value: {{port}}
{% endfor %}