static_resources:

    listeners:
      - name: listener_https
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 443
        filter_chains:
          - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_ws_to_ws
                use_remote_address: true
                upgrade_configs:
                - upgrade_type: websocket
                route_config:
                  name: local_route

                  virtual_hosts:
{% for host in query('inventory_hostnames', 'all') %}
{% if 'cockpit_host' in hostvars[host] %}
                  - name: {{hostvars[host]['cockpit_host']}}
                    domains:
                    - "{{hostvars[host]['cockpit_host']}}.{{domain}}"
                    routes:
                    - match:
                        prefix: "/"
                      route:
                        cluster: {{hostvars[host]['cockpit_host']}}
{% endif %}
{% if 'syncthing_host' in hostvars[host] %}
                  - name: {{hostvars[host]['syncthing_host']}}
                    domains:
                    - "{{hostvars[host]['syncthing_host']}}.{{domain}}"
                    routes:
                    - match:
                        prefix: "/"
                      route:
                        cluster: {{hostvars[host]['syncthing_host']}}
{% endif %}
{% if 'minimap_host' in hostvars[host] %}
                  - name: {{hostvars[host]['minimap_host']}}
                    domains:
                    - "{{hostvars[host]['minimap_host']}}.{{domain}}"
                    routes:
                    - match:
                        prefix: "/"
                      route:
                        cluster: {{hostvars[host]['minimap_host']}}
{% endif %}
{% endfor %}
                http_filters:
                - name: envoy.filters.http.router
            transport_socket:
              name: envoy.transport_sockets.tls
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                common_tls_context:
                  tls_certificates:
                  - certificate_chain:
                      filename: "/etc/envoy/fullchain.pem"
                    private_key:
                      filename: "/etc/envoy/privkey.pem"

    clusters:
{% for host in query('inventory_hostnames', 'all') %}
{% if 'cockpit_host' in hostvars[host] %}
      - name: {{hostvars[host]['cockpit_host']}}
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: {{hostvars[host]['cockpit_host']}}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{hostvars[host]['ansible_host']}}
                    port_value: 9090
{% endif %}
{% if 'syncthing_host' in hostvars[host] %}
      - name: {{hostvars[host]['syncthing_host']}}
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: {{hostvars[host]['syncthing_host']}}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{hostvars[host]['ansible_host']}}
                    port_value: 8384
{% endif %}
{% if 'minimap_host' in hostvars[host] %}
      - name: {{hostvars[host]['minimap_host']}}
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: {{hostvars[host]['minimap_host']}}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{hostvars[host]['ansible_host']}}
                    port_value: 8123
{% endif %}
{% endfor %}