---
- hosts:
  - localhost
  vars:
    tf_dir: "tf/{{workspace}}/{{deployment}}/{{version_major}}"
    certs_dir: "certs/{{workspace}}/{{deployment}}/{{version_major}}"
    regions: "{{quetz_region}}"

  pre_tasks:

  # - name: Adding ssh.keys
  #   shell: |
  #     eval "$(ssh-agent)"
  #     ssh-add .secrets/id_rsa
  #     ssh-add
  #   tags:
  #     - always

  - name: Add libvirt_host
    add_host:
      name: "{{libvirt_host}}"
      ansible_host:  "{{libvirt_host}}.{{domain}}"
      cockpit_host: "{{libvirt_cockpit_host}}"
      groups: libvirt_host
      ansible_user: "{{libvirt_user}}"
    when: libvirt_host is defined
    tags:
      - always

  - name: Debug libvirt_host group
    ansible.builtin.debug:
      msg: "{{ groups['libvirt_host']}}"
    when: groups['libvirt_host'] is defined
    tags:
      - always

  roles:
    - role: cloudimages
      when: provider=="libvirt"

    - role: certbot-ovh
    - role: certbot-cloudflare
    - role: terraform-openstack
      when: provider=="openstack"

- hosts:
    - libvirt_host
  roles:
    - system
    - nmcli
    - docker
    - firewalld
    - libvirt
    - resolved
    - cockpit
    - envoy
    - envoy-https
    - envoy-tcp
    - envoy-udp
    - user
    - syncthing-relaysrv
    - syncthing-discosrv
  vars:
    certs_dir: "certs/{{workspace}}/{{deployment}}/{{version_major}}"

- hosts:
    - instances
  roles:
    - system
    - cockpit
    - user
    - minecraft-bedrock
    - minecraft-bukkit
    - minecraft-papermc
    - syncthing
  vars:
    certs_dir: "certs/{{workspace}}/{{deployment}}/{{version_major}}"
    
- hosts:
    - quetz
  vars:
    certs_dir: "certs/{{workspace}}/{{deployment}}/{{version_major}}"
  roles:
    - system
    - certs
    - docker
    - quetz