all:
  hosts:
  children:
    quetz:
      hosts:
        quant-prod-quetz-1:
          alias: beta
          alias2: repo
          ansible_user: ubuntu
          domain: mamba.pm
          group: quetz
          ansible_host: 141.94.214.180