---
- hosts:
  - localhost

  tasks:
  - name: Set libvirt_endpoint
    set_fact:
      libvirt_endpoint: "{{libvirt_host}}"
    when: libvirt_endpoint is undefined and libvirt_host is defined
    tags:
      - always

  - name: Add libvirt_endpoint
    add_host:
      name: "{{ libvirt_endpoint }}"
      groups: libvirt_endpoint
      ansible_user: '{{ libvirt_user }}'
    when: libvirt_endpoint is defined
    tags:
      - always

  - name: Add libvirt_host
    add_host:
      name: "{{ libvirt_host }}"
      groups: libvirt_host
      ansible_user: '{{ libvirt_user }}'
    when: libvirt_host is defined
    tags:
      - always

  - name: Debug libvirt_endpoint group
    ansible.builtin.debug:
      msg: "{{ groups['libvirt_endpoint']}}"
    when: groups['libvirt_endpoint'] is defined
    tags:
      - always

  - name: Debug libvirt_host group
    ansible.builtin.debug:
      msg: "{{ groups['libvirt_host']}}"
    when: groups['libvirt_host'] is defined
    tags:
      - always

  roles:
    - cloudimages

- hosts: all
  gather_facts: true
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts
    tags:
      - facts

- hosts:
    - libvirt_host
  roles:
    - system
    - nmcli
    - docker
    - firewalld
    - libvirt
    - dnsmasq
    - resolved
    # - tpm
    - cockpit
    # - consul
    - envoy

# - hosts:
#     - libvirt_endpoint
#   roles:
#     - cloudimages
