
# For tasks is to work you need to run ssh-add on your local system
# And add 'ForwardAgent yes' to your local SSH configuration
# To enable Github authentifcation via SSH agent forwarding  

# - name: Clone quetz-deploy repository
#   git:
#     repo: git@github.com:mamba-org/quetz-deploy
#     dest: "/home/{{ansible_user}}/quetz-deploy"
#     accept_hostkey: yes

- name: Create quetz-deploy
  file: 
    path: /home/{{ansible_user}}/quetz-deploy
    state: directory
    recurse: yes


- name: Clone quetz
  git:
    repo: "{{quetz_repo}}"
    dest: "/home/{{ansible_user}}/quetz-deploy/quetz"
    accept_hostkey: yes
  ignore_errors: yes

- name: Clone quetz-frontend 
  git:
    repo: "{{quetz_frontend_repo}}"
    dest: /home/{{ansible_user}}/quetz-deploy/quetz-frontend
    accept_hostkey: yes

- name: Create quetz-data
  file: 
    path: /home/{{ansible_user}}/quetz-data/channels
    state: directory
    recurse: yes

- name: Create Dockerfile
  template:
    src: templates/Dockerfile
    dest: /home/{{ansible_user}}/quetz-deploy/Dockerfile

- name: Create docker-compose.yml
  template:
    src: templates/docker-compose.yml
    dest: /home/{{ansible_user}}/quetz-deploy/docker-compose.yml

- name: Create config.toml
  template:
    src: config.toml
    dest: /home/{{ansible_user}}/quetz-data/config.toml

- name: Create nginx.conf
  template:
    src: nginx.conf
    dest: /home/{{ansible_user}}/quetz-deploy/nginx.conf

- name: Create wait-for-it.sh
  template:
    src: templates/wait-for-it.sh
    dest: /home/{{ansible_user}}/quetz-deploy/wait-for-it.sh
    mode: '0755'