- name: Install syncthing-relaysrv
  become: yes
  apt:
    name: 
        - syncthing-relaysrv


- name: Enable syncthing@fabian
  become: yes
  service:
    name: syncthing-relaysrv
    state: started
    enabled: yes

- name: Allow syncthing-relaysrv Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 22067/tcp
    permanent: yes
    state: enabled
    immediate: true

- name: Allow syncthing-relaysrv Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 22070/tcp
    permanent: yes
    state: enabled
    immediate: true