- name: Get envoy
  become: yes 
  get_url:
    url: "https://github.com/pomerium/envoy-binaries/releases/download/v1.21.1/envoy-linux-amd64"
    dest: "/usr/local/bin/envoy"
    mode: '0755'

- name: Create envoy directory
  become: yes
  file:
    path: "/etc/envoy"
    state: directory