[general]
package_unpack_threads="{{quetz_general_package_unpack_threads}}"


[github]
# Register the app here: https://github.com/settings/applications/new
# the callback url should be <URL>/auth/github/authorize
client_id = "{{quetz_github_client_id}}"
client_secret = "{{quetz_github_client_secret}}"

[sqlalchemy]
database_url = "{{quetz_sqlalchemy_database_url}}"

[session]
secret = "{{quetz_session_secret}}"
https_only = "{{quetz_session_https_only}}"

[s3]
access_key = "{{quetz_s3_access_key}}"
secret_key = "{{quetz_s3_secret_key}}"
url = "{{quetz_s3_url}}"
region = "{{quetz_s3_region}}"
bucket_prefix="{{quetz_s3_bucket_prefix}}"
bucket_suffix="{{quetz_s3_bucket_suffix}}"

[users]
# users with owner role
admins = {{quetz_users_admins}}

[logging]
level = "{{quetz_logging_level}}"
file = "{{quetz_logging_file}}"

