version: "3.8"

services:
  db:
    image: postgres:13.6
    # debug
    # command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=quetz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/ubuntu/postgres-data:/var/lib/postgresql/data:z
    healthcheck:
      test: pg_isready -U postgres
      interval: 20s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: quetz start /quetz-data --port 8000 --host 0.0.0.0 --proxy-headers --reload --log-level=trace
    volumes:
      - /home/ubuntu/quetz-data:/quetz-data:z
    environment:
      - FORWARDED_ALLOW_IPS=*
    depends_on:
      - migration
      - db

  migration:
    build: .
    command: bash -c "wait-for-it.sh db:5432 && quetz init-db /quetz-data"
    volumes:
      - /home/ubuntu/quetz-data:/quetz-data:z
    depends_on:
      - db

  nginx_proxy:
    image: nginx
    container_name: nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - web
