- name: Create resolved Config
  become: yes
  template:
    src: "resolved.conf"
    dest: "/etc/systemd/resolved.conf"
    mode: '0644'
    owner: "root"
    group: "root"
  notify:
    - Restart resolved

- name: Enable systemd-resolved
  become: yes
  service:
    name: systemd-resolved
    state: started
    enabled: true

- name: Create a symbolic link
  become: yes
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes