- include_role:
    name: nmcli

- name: Install firewalld
  become: yes
  apt:
    name: 
        - firewalld 
    state: present
    update_cache: no


- name: Enable firewalld
  become: yes
  service:
    name: firewalld
    state: started
    enabled: true

- name: Set public interface
  become: yes
  ansible.posix.firewalld:
    zone: public
    interface: "{{ ansible_default_ipv4.interface }}"
    permanent: true
    immediate: true
    state: enabled

# - name: Allow SSH-Forwarding
#   become: yes
#   ansible.posix.firewalld:
#     zone: public
#     port: 22001-22099/tcp
#     permanent: yes
#     state: enabled
#     immediate: true


# - name: Permit https traffic
#   become: yes
#   ansible.posix.firewalld:
#     service: https
#     zone: public
#     permanent: yes
#     immediate: yes
#     state: enabled

# - ansible.posix.firewalld:
#     zone: public
#     masquerade: yes
#     permanent: true
#     immediate: true
#     state: enabled


