static_resources:
    listeners:
      - name: listener_22002
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 22002
        filter_chains:
          - filters:
              - name: envoy.filters.network.tcp_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                  stat_prefix: destination
                  cluster: cluster_22002
{% for port in range(25565,25585) %}
      - name: listener_{{port}}
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{port}}
        filter_chains:
          - filters:
              - name: envoy.filters.network.tcp_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                  stat_prefix: destination
                  cluster: cluster_{{port}}
{% endfor %}

    clusters:
      - name: cluster_22002
        connect_timeout: 30s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: cluster_22002
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: 100.100.0.2
                        port_value: 22

{% for port in range(25565,25585) %}
      - name: cluster_{{port}}
        connect_timeout: 30s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: cluster_{{port}}
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: 100.100.0.2
                        port_value: {{port}}
{% endfor %}
