- name: Install tools + dependencies
  become: yes
  apt:
    name: 
        - openjdk-17-jre


- name: Create minecraft-bukkit service config
  become: yes
  template:
    src: "{{item}}"
    dest: "/etc/systemd/system/{{item}}"
    mode: '0644'
  with_items:
    - minecraft-bukkit.service
  notify:
    - restart minecraft-bukkit

- name: Enable minecraft-bukkit
  become: yes
  service:
    name: minecraft-bukkit
    state: started
    enabled: yes


- name: Allow Minecraft-Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 25565/udp
    permanent: yes
    state: enabled
    immediate: true


- name: Allow Minecraft-Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 25565/tcp
    permanent: yes
    state: enabled
    immediate: true

- name: Allow Minecraft-Ports
  become: yes
  ansible.posix.firewalld:
    zone: public
    port: 25575/tcp
    permanent: yes
    state: enabled
    immediate: true
