static_resources:
    listeners:
      - name: minecraft_19132
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 19132
        filter_chains:
          - filters:
              - name: envoy.filters.network.tcp_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                  stat_prefix: destination
                  cluster: cluster_19132
  
    clusters:
      - name: cluster_19132
        connect_timeout: 30s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: cluster_19132
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: 100.100.0.2
                        port_value: 19132

